services:
  - type: web
    name: transport-dashboard-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
      - key: MONGODB_URL
        sync: false
      - key: DATABASE_NAME
        value: transport_data_db
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
